language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: fSy+5fkFhl11YGzlfdn5zVJaJ3AcYvQQpLMle5OywYedKN6/FOXmo8YPU0aZJTbq0tNiHbz1rY9jYyfdcW2vhHUeNMwku4z/bkkn4J5ZAvBtIJscJZJ3Mz9NTKjFJNgqNt18guA/+7SkJeGaX2rMblPQU0S+FxPrKeyUVdXDDXijdinelvSCDLw+psEbpQIt3/fdxewwLVFfBqZLNF1Wxcxk257EBf/GQDQGyQni2CJCIKjByJVylb0/SteL0UEfmF67R67jkTay26Xm5UjG8D7qUNvDxNut4/acCRT6VxqP4/+MS1ChZg+tutUKpWgeP6ZV1C+6Sa4WDJdg6Y14cSO67CJda9BdAHMaUAbcCj723PCyMCl/w6t+o4AijZX9ZUXRD+6PD09AzRpN2dqbQ+NEUg6aXq/+oAByTVBps4SCc9EG5FSNc/7EOu7iNFVNyKe+qRIVX6z+Q6nF622u/CI1BkAfO1LiKlm8ydnFCKU3u/mvO/qCCGb2K3OGikj1ppQH+5p44DUXK43VLz3FEZRNzWakDF3lVWwDJwu+u7I0EAgfwWt5J5dnjNlrPK6S4ceuOdsdUuHt/gsAy8iwFbyzEniFLOCJ4pvDWekoTkwEbMYwt6WzNIsGBPQHxqyY/xH9vAGGJcD22gFLm/bH+xbGVyDNNz6zge19owMb4hM=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
