language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: myLACtSq9ItsnMjK07k6RHi3MuCLhch4QTCM80/n5LmWodlu1sAGtLPfbCULxjSiZf4x9hqYoLVXJQ4ZhUQ4DAjUroP3pQYuF7cMMuxFoxz7SCHgUNwODJsYwpjXZh2TogBkAv/NYV3P3ArPweo7N0m10rfs6lFLvvGHHyJVJNqL/VAUUzugNRLcqJOQdwadPQ3nzj/EdRtE7t3aNFSaZ+WCLdbMEvyNRtpeLDEUjpnWf1yIWmTKyA8XK91dfBBabchoNpyMVRsn2QFuqM2mk9xkDqyCQUb3iUrXTTdQkRUQAYJsw4I+9Xp8NaqFfKN1mDQiysC/tLBP9NaD7B/7Naoz/usjWwz/oiJ9IFD7l7tL7Ka6ob1kuHCrtie9n6JxBuZeKUnTs3hwXcsYRei5zljRGEG1V3SJFP22EnuwYxlR6P8RQxFVRNvhk4nigpwh0upFetKTaPryw24BZ6+CdOaInQKtepv+GXFDzY25W46R1x+I/3i6bDwIBqqFq892QYiNJxuQaYTdqC675EgzunNpn7JWxhrsH9OR9H7xRaS3s3J+nJocZ1LuElBVPV4LykaZdtzooncHHeuGet0X7BB30UVPuTF8+GcPePxRNbp++OczqOkYdbvSL1ViD3URi99oKK3rNQbMICZIoN5CkMyANy8SBFNSN6VLnaaXNMk=
jdk:
- oraclejdk8
sudo: false
script: mvn --settings .travis-settings.xml  -Pdeploy  -DskipTests=false -B -Dgpg.skip=true
  clean test deploy
