language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: tiGlG3A82qWeWuFsCBPISROgIoYNq/cXdR/niRiC91Jw+mghGw5B5xG7dSpsSkuMOr03P22aCNmJV8kIkkL04EYTaxhjEV8N8wcoQeDRQYLyxAolOjfOVyylVAMj2fxd7BdyBBe1Y+PqnRTC+9IEy9kwfOkKcgnLEUUjAwzNxthvhFAhkd5CqgZ4EHEP39MhKmieJakjIAcvBYnnX+2YrurYjYc6BTLP6DtcvMw7qdMYLmEtqn8XL5WypAy6qpGlme6xPrKhY6V1DJ5xkJRlo9Uu3+vtx2VTTvxTnqPJSvgfCRtWAe87R0wk1/HaoMD39/FP6WQz7PMFq1u/MC43XMiMNRvZGsOYdSMH42bDneLyYZxulGjq559K8RGNNfQwNbbpApPDXx64anNVdzfB/xh3tQjKWxnrid06eE5nFroyMjV2wHzZAmcWXxcgKI+3hg1VXK/K6s1VS4gldxcyrzLfRG373k3HynEnqIEGpkzWNZnoGR2i7vUe0odae5VK8Sx+ian8qnfPZ6VF8FSzpFU6KFm30NbZKRxtldsMk3YZdiiX41eyza6fvmOY+Sn+8/biWxbLd5f9bAxrRaKQQYYTKOIRNhZiaaCKFnA+Ls6lgTlXj/kyxlUd/NgyNUk5ai8f9GSLMislNRQnf9h0LAKYhkPq8PDI/nawNpSNo/Q=
jdk:
- opendk8
sudo: false
script: mvn --settings .travis-settings.xml  -Pdeploy  -DskipTests=false -B -Dgpg.skip=true
  clean test deploy
